export const colors = {
  NEUTRAL_100: "--colors-neutral-100",
  NEUTRAL_90: "--colors-neutral-90",
  NEUTRAL_80: "--colors-neutral-80",
  NEUTRAL_70: "--colors-neutral-70",
  NEUTRAL_60: "--colors-neutral-60",
  NEUTRAL_50: "--colors-neutral-50",
  NEUTRAL_40: "--colors-neutral-40",
  NEUTRAL_30: "--colors-neutral-30",
  NEUTRAL_20: "--colors-neutral-20",
  NEUTRAL_10: "--colors-neutral-10",
  NEUTRAL_5: "--colors-neutral-5",
  NEUTRAL_WHITE: "--colors-neutral-white",
  PRIMARY_100: "--colors-primary-100",
  PRIMARY_90: "--colors-primary-90",
  PRIMARY_80: "--colors-primary-80",
  PRIMARY_70: "--colors-primary-70",
  PRIMARY_60: "--colors-primary-60",
  PRIMARY_50: "--colors-primary-50",
  PRIMARY_40: "--colors-primary-40",
  PRIMARY_30: "--colors-primary-30",
  PRIMARY_20: "--colors-primary-20",
  PRIMARY_10: "--colors-primary-10",
  PRIMARY_5: "--colors-primary-5",
  PRIMARY_WHITE: "--colors-primary-white",
  STROKE_BLUE: "--colors-stroke-blue",
  STROKE_10: "--colors-stroke-10",
  STROKE_5: "--colors-stroke-5",
  BACKGROUND_100: "--colors-background-100",
  BACKGROUND_50: "--colors-background-50",
  BACKGROUND_GRAY: "--colors-background-gray",
  BACKGROUND_5: "--colors-background-5",
  BACKGROUND_BLUE: "--colors-background-blue",
  SYSTEM_WARNING: "--colors-system-warning",
  SYSTEM_SUCCESS: "--colors-system-success",
  BORDER_COLOR : "--colors-border-color"
};
