export const popularPortfolioData = [
  {
    id: "abc",
    likes: 93,
    bookmark: 3,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "김영수",
    title: "편리한 생활 솔루션",
    src: "/portfolioImg/portfolioImg1.png",
  },
  {
    id: "abc",
    likes: 284,
    bookmark: 73,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "박지현",
    title: "디지털 라이프 스타일",
    src: "/portfolioImg/portfolioImg2.png",
  },
  {
    id: "abc",
    likes: 106,
    bookmark: 130,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "이은지",
    title: "사용자 중심의 편의성",
    src: "/portfolioImg/portfolioImg3.png",
  },
  {
    id: "abc",
    likes: 35,
    bookmark: 171,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "오성민",
    title: "스마트한 일상체험",
    src: "/portfolioImg/portfolioImg4.png",
  },
  {
    id: "abc",
    likes: 87,
    bookmark: 294,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "김준영",
    title: "혁신적인 서비스 디자인",
    src: "/portfolioImg/portfolioImg5.png",
  },
  {
    id: "abc",
    likes: 40,
    bookmark: 127,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "최수빈",
    title: "머신러닝을 활용한 서비스",
    src: "/portfolioImg/portfolioImg6.png",
  },
  {
    id: "abc",
    likes: 298,
    bookmark: 192,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "이서연",
    title: "사회 문제 해결을 위한 서비스",
    src: "/portfolioImg/portfolioImg7.png",
  },
  {
    id: "abc",
    likes: 287,
    bookmark: 193,
    category: "webplan",
    label: "웹 기획",
    userName: "김동현",
    title: "모바일 퍼스트 디자인",
    src: "/portfolioImg/portfolioImg1.png",
  },
  {
    id: "abc",
    likes: 138,
    bookmark: 244,
    category: "webplan",
    label: "웹 기획",
    userName: "임지원",
    title: "사용자 경험 개선",
    src: "/portfolioImg/portfolioImg2.png",
  },
  {
    id: "abc",
    likes: 170,
    bookmark: 197,
    category: "webplan",
    label: "웹 기획",
    userName: "이승민",
    title: "현대적이고 간결한 디자인",
    src: "/portfolioImg/portfolioImg3.png",
  },
  {
    id: "abc",
    likes: 89,
    bookmark: 218,
    category: "webplan",
    label: "웹 기획",
    userName: "오지훈",
    title: "웹 생태계의 혁신",
    src: "/portfolioImg/portfolioImg4.png",
  },
  {
    id: "abc",
    likes: 136,
    bookmark: 136,
    category: "webplan",
    label: "웹 기획",
    userName: "서민준",
    title: "사용자 중심의 웹 경험",
    src: "/portfolioImg/portfolioImg5.png",
  },
  {
    id: "abc",
    likes: 122,
    bookmark: 9,
    category: "webplan",
    label: "웹 기획",
    userName: "장세진",
    title: "웹 애니메이션과 효과",
    src: "/portfolioImg/portfolioImg6.png",
  },
  {
    id: "abc",
    likes: 180,
    bookmark: 40,
    category: "webplan",
    label: "웹 기획",
    userName: "김서연",
    title: "웹 플랫폼의 미래",
    src: "/portfolioImg/portfolioImg7.png",
  },
  {
    id: "abc",
    likes: 50,
    bookmark: 161,
    category: "appplan",
    label: "앱 기획",
    userName: "유민서",
    title: "편리한 모바일 앱",
    src: "/portfolioImg/portfolioImg1.png",
  },
  {
    id: "abc",
    likes: 98,
    bookmark: 127,
    category: "appplan",
    label: "앱 기획",
    userName: "한재우",
    title: "스마트폰을 활용한 라이프스타일",
    src: "/portfolioImg/portfolioImg2.png",
  },
  {
    id: "abc",
    likes: 36,
    bookmark: 10,
    category: "appplan",
    label: "앱 기획",
    userName: "장시현",
    title: "사용자 중심의 앱 경험",
    src: "/portfolioImg/portfolioImg3.png",
  },
  {
    id: "abc",
    likes: 185,
    bookmark: 150,
    category: "appplan",
    label: "앱 기획",
    userName: "강민지",
    title: "인공지능과 함께하는 앱",
    src: "/portfolioImg/portfolioImg4.png",
  },
  {
    id: "abc",
    likes: 270,
    bookmark: 76,
    category: "appplan",
    label: "앱 기획",
    userName: "최은서",
    title: "모바일 앱의 미래",
    src: "/portfolioImg/portfolioImg5.png",
  },
  {
    id: "abc",
    likes: 236,
    bookmark: 245,
    category: "appplan",
    label: "앱 기획",
    userName: "이은주",
    title: "사용자 중심의 디자인",
    src: "/portfolioImg/portfolioImg6.png",
  },
  {
    id: "abc",
    likes: 298,
    bookmark: 189,
    category: "appplan",
    label: "앱 기획",
    userName: "박예원",
    title: "혁신적인 앱 서비스",
    src: "/portfolioImg/portfolioImg7.png",
  },
  {
    id: "abc",
    likes: 111,
    bookmark: 222,
    category: "webdesign",
    label: "웹 디자인",
    userName: "김수빈",
    title: "webdesign의 미적 감각",
    src: "/portfolioImg/portfolioImg1.png",
  },
  {
    id: "abc",
    likes: 163,
    bookmark: 199,
    category: "webdesign",
    label: "웹 디자인",
    userName: "이지민",
    title: "모던한 웹 비주얼",
    src: "/portfolioImg/portfolioImg2.png",
  },
  {
    id: "abc",
    likes: 242,
    bookmark: 186,
    category: "webdesign",
    label: "웹 디자인",
    userName: "김태현",
    title: "웹사이트 디자인 트렌드",
    src: "/portfolioImg/portfolioImg3.png",
  },
  {
    id: "abc",
    likes: 228,
    bookmark: 186,
    category: "webdesign",
    label: "웹 디자인",
    userName: "정유진",
    title: "웹 그래픽스와 일러스트레이션",
    src: "/portfolioImg/portfolioImg4.png",
  },
  {
    id: "abc",
    likes: 80,
    bookmark: 237,
    category: "webdesign",
    label: "웹 디자인",
    userName: "장재윤",
    title: "사용자 친화적인 웹",
    src: "/portfolioImg/portfolioImg5.png",
  },
  {
    id: "abc",
    likes: 189,
    bookmark: 45,
    category: "webdesign",
    label: "웹 디자인",
    userName: "박진영",
    title: "웹 브랜딩과 아이덴티티",
    src: "/portfolioImg/portfolioImg6.png",
  },
  {
    id: "abc",
    likes: 158,
    bookmark: 229,
    category: "webdesign",
    label: "웹 디자인",
    userName: "서승훈",
    title: "플랫 디자인의 진화",
    src: "/portfolioImg/portfolioImg7.png",
  },
  {
    id: "abc",
    likes: 188,
    bookmark: 104,
    category: "appdesign",
    label: "앱 디자인",
    userName: "김민우",
    title: "모바일 앱 UI/UX 디자인",
    src: "/portfolioImg/portfolioImg1.png",
  },
  {
    id: "abc",
    likes: 215,
    bookmark: 27,
    category: "appdesign",
    label: "앱 디자인",
    userName: "이수빈",
    title: "앱 인터페이스 디자인",
    src: "/portfolioImg/portfolioImg2.png",
  },
  {
    id: "abc",
    likes: 139,
    bookmark: 257,
    category: "appdesign",
    label: "앱 디자인",
    userName: "박준호",
    title: "현대적인 앱 그래픽 디자인",
    src: "/portfolioImg/portfolioImg3.png",
  },
  {
    id: "abc",
    likes: 253,
    bookmark: 128,
    category: "appdesign",
    label: "앱 디자인",
    userName: "김지우",
    title: "모바일 앱의 디자인 트렌드",
    src: "/portfolioImg/portfolioImg4.png",
  },
  {
    id: "abc",
    likes: 52,
    bookmark: 141,
    category: "appdesign",
    label: "앱 디자인",
    userName: "홍예진",
    title: "세련된 appdesign",
    src: "/portfolioImg/portfolioImg5.png",
  },
  {
    id: "abc",
    likes: 48,
    bookmark: 180,
    category: "appdesign",
    label: "앱 디자인",
    userName: "이시우",
    title: "편리한 모바일 경험",
    src: "/portfolioImg/portfolioImg6.png",
  },
  {
    id: "abc",
    likes: 221,
    bookmark: 38,
    category: "appdesign",
    label: "앱 디자인",
    userName: "정지수",
    title: "최신 appdesign 트렌드",
    src: "/portfolioImg/portfolioImg7.png",
  },
];

export const PopularProjectData = [
  // Sorted by category: 'design'
  {
    tag: ["D-23", "7주"],
    heading: "그래픽 디자인 챌린지",
    category: "design",
    label: "디자인",
    description:
      "창의적인 그래픽 디자인을 통해 새로운 아이디어를 제시해주실 디자이너 분들을 모집합니다. 함께 도전해봐요!",
    recruitmentMembers: ["디자이너 4"],
    imageUrl: "/prjImg/prjImage1.png",
    deadline: "2024-02-12",
    views: 150,
  },
  {
    tag: ["D-20", "6주"],
    heading: "웹 서비스 디자인 프로젝트",
    category: "design",
    label: "디자인",
    description:
      "5주 동안 웹 서비스 기획하고 디자인 같이 해서 포트폴리오 제작하는 프로젝트입니다.",
    recruitmentMembers: ["기획자 3", "디자이너 5"],
    imageUrl: "/prjImg/prjImage3.png",
    deadline: "2024-02-10",
    views: 200,
  },
  {
    tag: ["D-13", "7주"],
    heading: "그래픽 디자인 챌린지",
    category: "design",
    label: "디자인",
    description:
      "창의적인 그래픽 디자인으로 참가자들을 감동시킬 디자이너를 찾습니다. 함께 도전해봐요!",
    recruitmentMembers: ["디자이너 3"],
    imageUrl: "/prjImg/prjImage2.png",
    deadline: "2024-02-16",
    views: 125,
  },

  // Sorted by category: 'uxui'
  {
    tag: ["D-15", "8주"],
    heading: "UX/UI 디자인 챌린지",
    category: "uxui",
    label: "UX/UI",
    description:
      "혁신적인 UX/UI 디자인으로 사용자 경험을 향상시킬 디자이너를 찾습니다. 도전해보세요!",
    recruitmentMembers: ["디자이너 2"],
    imageUrl: "/prjImg/prjImage1.png",
    deadline: "2024-02-20",
    views: 120,
  },
  {
    tag: ["D-25", "8주"],
    heading: "UX/UI 리뉴얼 프로젝트",
    category: "uxui",
    label: "UX/UI",
    description:
      "기존 서비스의 UX/UI를 혁신적으로 개선할 디자이너를 찾습니다. 도전하세요!",
    recruitmentMembers: ["디자이너 3"],
    imageUrl: "/prjImg/prjImage2.png",
    deadline: "2024-02-14",
    views: 110,
  },
  {
    tag: ["D-12", "6주"],
    heading: "모바일 앱 디자인 챌린지",
    category: "uxui",
    label: "UX/UI",
    description:
      "효율적이고 매력적인 모바일 앱 디자인으로 참가자들을 사로잡을 디자이너를 찾습니다. 도전해보세요!",
    recruitmentMembers: ["디자이너 4"],
    imageUrl: "/prjImg/prjImage3.png",
    deadline: "2024-02-18",
    views: 160,
  },

  // Sorted by category: 'develop'
  {
    tag: ["D-5", "6주"],
    heading: "개발 챌린지",
    category: "develop",
    label: "개발",
    description:
      "현존하는 문제를 해결할 혁신적인 소프트웨어를 개발할 개발자를 모집합니다. 도전하세요!",
    recruitmentMembers: ["개발자 5"],
    imageUrl: "/prjImg/prjImage2.png",
    deadline: "2024-02-05",
    views: 80,
  },
  {
    tag: ["D-2", "9주"],
    heading: "웹 개발 챌린지",
    category: "develop",
    label: "개발",
    description:
      "최신 웹 개발 기술을 활용하여 혁신적인 웹 애플리케이션을 개발할 개발자를 찾습니다. 도전하세요!",
    recruitmentMembers: ["개발자 2"],
    imageUrl: "/prjImg/prjImage3.png",
    deadline: "2024-02-07",
    views: 70,
  },
  {
    tag: ["D-17", "6주"],
    heading: "GEN AI 해커톤 참가",
    category: "develop",
    label: "개발",
    description:
      "경력 상관없이 인공지능 관심 있으신 분들, 책임감 있으신 분들 같이 6주 동안 해커톤 준비해봐요~!",
    recruitmentMembers: ["디자이너 1", "개발자 2"],
    imageUrl: "/prjImg/prjImage1.png",
    deadline: "2024-02-21",
    views: 200,
  },

  // Sorted by category: 'plan'
  {
    tag: ["D-10", "9주"],
    heading: "기획 챌린지",
    category: "plan",
    label: "기획",
    description:
      "창의적인 기획력으로 프로젝트를 성공적으로 이끌어낼 기획자를 찾습니다. 도전해주세요!",
    recruitmentMembers: ["기획자 1"],
    imageUrl: "/prjImg/prjImage2.png",
    deadline: "2024-02-08",
    views: 100,
  },
  {
    tag: ["D-18", "5주"],
    heading: "기획 아이디어 챌린지",
    category: "plan",
    label: "기획",
    description:
      "독특하고 혁신적인 기획 아이디어를 제시해줄 기획자를 모집합니다. 도전해보세요!",
    recruitmentMembers: ["기획자 4"],
    imageUrl: "/prjImg/prjImage1.png",
    deadline: "2024-02-22",
    views: 85,
  },
  {
    tag: ["D-7", "9주"],
    heading: "기획 프로토타이핑 챌린지",
    category: "plan",
    label: "기획",
    description:
      "기획 아이디어를 프로토타입으로 구현할 능력 있는 기획자를 찾습니다. 도전해보세요!",
    recruitmentMembers: ["기획자 5"],
    imageUrl: "/prjImg/prjImage3.png",
    deadline: "2024-02-09",
    views: 170,
  },

  // Sorted by category: 'etc'
  {
    tag: ["D-30", "5주"],
    heading: "기타 챌린지",
    category: "etc",
    label: "기타",
    description:
      "독특하고 창의적인 아이디어를 가진 참가자들을 기다립니다. 함께 도전해보세요!",
    recruitmentMembers: ["기획자 3"],
    imageUrl: "/prjImg/prjImage3.png",
    deadline: "2024-02-25",
    views: 180,
  },
  {
    tag: ["D-8", "7주"],
    heading: "메타버스 브랜딩 프로젝트",
    category: "etc",
    label: "기타",
    description:
      "MZ 세대를 타깃으로 메타버스 플랫폼 브랜딩 해 주실 기획자 분, 기획서 디자인 해주실 디자이너 분들 모십니다!",
    recruitmentMembers: ["기획자 3", "디자이너 5"],
    imageUrl: "/prjImg/prjImage2.png",
    deadline: "2024-02-17",
    views: 200,
  },
  {
    tag: ["D-28", "6주"],
    heading: "기타 디자인 이벤트",
    category: "etc",
    label: "기타",
    description:
      "독창적이고 다양한 분야에서 놀라운 디자인을 제시해줄 참가자를 기다립니다. 함께 참여해보세요!",
    recruitmentMembers: ["디자이너 2"],
    imageUrl: "/prjImg/prjImage1.png",
    deadline: "2024-02-13",
    views: 95,
  },
];

export const recruitData = [
  {
    id: "recruitment1",
    deadline: "2024-02-05",
    title: "[스팩폴리오] 블록체인 엔지니어 채용",
    position: "블록체인 엔지니어",
    company: "체인마스터 주식회사",
    category: "backend",
    views: 56,
  },
  {
    id: "recruitment2",
    deadline: "2024-02-12",
    title: "[스팩폴리오] 시스템 아키텍처 채용",
    position: "시스템 아키텍처",
    company: "아키텍츠웍스 기술",
    category: "backend",
    views: 124,
  },
  {
    id: "recruitment3",
    deadline: "2024-02-15",
    title: "[스팩폴리오] 빅데이터 엔지니어 채용",
    position: "빅데이터 엔지니어",
    company: "빅데이터랩 주식회사",
    category: "backend",
    views: 37,
  },
  {
    id: "recruitment4",
    deadline: "2024-02-18",
    title: "[스팩폴리오] 클라우드 아키텍트 채용",
    position: "클라우드 아키텍트",
    company: "클라우드비전 주식회사",
    category: "backend",
    views: 180,
  },
  {
    id: "recruitment5",
    deadline: "2024-02-20",
    title: "[스팩폴리오] 머신러닝 엔지니어 채용",
    position: "머신러닝 엔지니어",
    company: "머신마스터 기술",
    category: "backend",
    views: 98,
  },
  {
    id: "recruitment6",
    deadline: "2024-02-10",
    title: "[스팩폴리오] 보안 엔지니어 채용",
    position: "보안 엔지니어",
    company: "시큐어티랩 주식회사",
    category: "backend",
    views: 72,
  },
  {
    id: "recruitment7",
    deadline: "2024-02-25",
    title: "[스팩폴리오] 리액트 개발자 채용",
    position: "리액트 개발자",
    company: "리액트마스터 주식회사",
    category: "frontend",
    views: 150,
  },
  {
    id: "recruitment8",
    deadline: "2024-02-28",
    title: "[스팩폴리오] 프론트엔드 엔지니어 채용",
    position: "프론트엔드 엔지니어",
    company: "프론트마스터 기술",
    category: "frontend",
    views: 45,
  },
  {
    id: "recruitment9",
    deadline: "2024-02-10",
    title: "[스팩폴리오] Angular 개발자 채용",
    position: "Angular 개발자",
    company: "앵귤러랩 주식회사",
    category: "frontend",
    views: 120,
  },
  {
    id: "recruitment10",
    deadline: "2024-02-03",
    title: "[스팩폴리오] 웹 디자이너 채용",
    position: "웹 디자이너",
    company: "웹스타 주식회사",
    category: "frontend",
    views: 30,
  },
  {
    id: "recruitment11",
    deadline: "2024-02-15",
    title: "[스팩폴리오] Vue.js 개발자 채용",
    position: "Vue.js 개발자",
    company: "뷰마스터 주식회사",
    category: "frontend",
    views: 180,
  },
  {
    id: "recruitment12",
    deadline: "2024-02-28",
    title: "[스팩폴리오] 프론트엔드 디자이너 채용",
    position: "프론트엔드 디자이너",
    company: "디자인마스터 주식회사",
    category: "frontend",
    views: 92,
  },
  {
    id: "recruitment13",
    deadline: "2024-02-18",
    title: "[스팩폴리오] UX/UI 디자이너 채용",
    position: "UX/UI 디자이너",
    company: "UX랩 주식회사",
    category: "designer",
    views: 22,
  },
  {
    id: "recruitment14",
    deadline: "2024-02-20",
    title: "[스팩폴리오] 그래픽 디자이너 채용",
    position: "그래픽 디자이너",
    company: "그래픽스마스터 기술",
    category: "designer",
    views: 160,
  },
  {
    id: "recruitment15",
    deadline: "2024-02-22",
    title: "[스팩폴리오] UI/UX 디자이너 채용",
    position: "UI/UX 디자이너",
    company: "디자인비전 주식회사",
    category: "designer",
    views: 75,
  },
  {
    id: "recruitment16",
    deadline: "2024-02-25",
    title: "[스팩폴리오] 모바일 앱 디자이너 채용",
    position: "모바일 앱 디자이너",
    company: "앱스튜디오 주식회사",
    category: "designer",
    views: 130,
  },
  {
    id: "recruitment17",
    deadline: "2024-02-28",
    title: "[스팩폴리오] 시각 디자이너 채용",
    position: "시각 디자이너",
    company: "시각마스터 주식회사",
    category: "designer",
    views: 50,
  },
  {
    id: "recruitment18",
    deadline: "2024-02-03",
    title: "[스팩폴리오] UX 플래너 채용",
    position: "UX 플래너",
    company: "UX플래닛 주식회사",
    category: "planner",
    views: 85,
  },
  {
    id: "recruitment19",
    deadline: "2024-02-15",
    title: "[스팩폴리오] UI 플래너 채용",
    position: "UI 플래너",
    company: "UI플래닛 주식회사",
    category: "planner",
    views: 110,
  },
  {
    id: "recruitment20",
    deadline: "2024-02-28",
    title: "[스팩폴리오] 디자인 기획자 채용",
    position: "디자인 기획자",
    company: "디자인플래닛 주식회사",
    category: "planner",
    views: 45,
  },
  {
    id: "recruitment21",
    deadline: "2024-02-25",
    title: "[스팩폴리오] 프로덕트 매니저 채용",
    position: "프로덕트 매니저",
    company: "프로덕트랩 주식회사",
    category: "planner",
    views: 195,
  },
  {
    id: "recruitment22",
    deadline: "2024-02-18",
    title: "[스팩폴리오] 모바일 앱 기획자 채용",
    position: "모바일 앱 기획자",
    company: "앱기획랩 주식회사",
    category: "planner",
    views: 75,
  },
  {
    id: "recruitment23",
    deadline: "2024-02-20",
    title: "[스팩폴리오] UX/UI 기획자 채용",
    position: "UX/UI 기획자",
    company: "기획마스터 주식회사",
    category: "planner",
    views: 145,
  },
  {
    id: "recruitment24",
    deadline: "2024-02-22",
    title: "[스팩폴리오] AI 기술자 채용",
    position: "AI 기술자",
    company: "로보테크 주식회사",
    category: "backend",
    views: 32,
  },
  {
    id: "recruitment25",
    deadline: "2024-02-18",
    title: "[스팩폴리오] 디자이너 채용",
    position: "디자이너",
    company: "디자인마스터 주식회사",
    category: "designer",
    views: 56,
  },
];

export const hotCreatorCarouselData = [
  {
    id: "a1",
    userName: "김지후",
    userJob: "UXUI 디자이너",
    imageUrl: [
      "/portfolioPageImg/carousel-1.png",
      "/portfolioPageImg/carousel-3.png",
      "/portfolioPageImg/carousel-5.png",
    ],
    avatarSrc: "/portfolioPageImg/carouselAvatar-1.png",
  },
  {
    id: "a2",
    userName: "오민준",
    userJob: "그래픽 디자이너",
    imageUrl: [
      "/portfolioPageImg/carousel-2.png",
      "/portfolioPageImg/carousel-4.png",
      "/portfolioPageImg/carousel-6.png",
    ],
    avatarSrc: "/portfolioPageImg/carouselAvatar-2.png",
  },
  {
    id: "a3",
    userName: "김지윤",
    userJob: "웹 디자이너",
    imageUrl: [
      "/portfolioPageImg/carousel-7.png",
      "/portfolioPageImg/carousel-1.png",
      "/portfolioPageImg/carousel-8.png",
    ],
    avatarSrc: "/portfolioPageImg/carouselAvatar-3.png",
  },
  {
    id: "a4",
    userName: "김아영",
    userJob: "제품 디자이너",
    imageUrl: [
      "/portfolioPageImg/carousel-2.png",
      "/portfolioPageImg/carousel-9.png",
      "/portfolioPageImg/carousel-4.png",
    ],
    avatarSrc: "/portfolioPageImg/carouselAvatar-1.png",
  },
  {
    id: "a5",
    userName: "김두한",
    userJob: "일러스트레이터",
    imageUrl: [
      "/portfolioPageImg/carousel-6.png",
      "/portfolioPageImg/carousel-3.png",
      "/portfolioPageImg/carousel-9.png",
    ],
    avatarSrc: "/portfolioPageImg/carouselAvatar-2.png",
  },
];

export const portfolioRecommendData = [
  {
    id: "ab1",
    likes: 93,
    bookmark: 33,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "이재교",
    title: "리유저블 텀블러 서비스, Re:ttle",
    src: "/portfolioPageImg/Image-Recommend-1.png",
  },
  {
    id: "ab2",
    likes: 103,
    bookmark: 101,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "이재한",
    title: "짐보관 서비스, Beeum[비움]",
    src: "/portfolioPageImg/Image-Recommend-2.png",
  },
  {
    id: "ab3",
    likes: 41,
    bookmark: 55,
    category: "serviceplan",
    label: "서비스 기획",
    userName: "홍길동",
    title: "뉴스를 밀도있게, MEALDO",
    src: "/portfolioPageImg/Image-Recommend-3.png",
  },
];

export const portfolioListData = [
  {
    id: "abc1",
    likes: 672,
    bookmark: 1124,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김잼 kimjam",
    title: "DDP 겨울축제 x 김잼",
    src: "/portfolioPageImg/Image-1.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-0.png",
  },
  {
    id: "abc2",
    likes: 347,
    bookmark: 715,
    category: "design",
    label: "디자인",
    username: "바이든",
    title: "일러스트 포스터: Strange world",
    src: "/portfolioPageImg/Image-2.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-1.png",
  },
  {
    id: "abc3",
    likes: 834,
    bookmark: 1407,
    category: "serviceplan",
    label: "서비스 기획",
    username: "조서아",
    title: "The Beatles 드로잉 모음",
    src: "/portfolioPageImg/Image-3.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-2.png",
  },
  {
    id: "abc4",
    likes: 1291,
    bookmark: 1308,
    category: "design",
    label: "디자인",
    username: "윤수민",
    title: "23 Portfolio / 23 포트폴리오",
    src: "/portfolioPageImg/Image-4.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-3.png",
  },
  {
    id: "abc5",
    likes: 1014,
    bookmark: 1262,
    category: "serviceplan",
    label: "서비스 기획",
    username: "Yumi Bae",
    title: "라이프 스타일 브랜드 Wiggle Wiggle - 컨셉 일러스트 작업",
    src: "/portfolioPageImg/Image-5.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-4.png",
  },
  {
    id: "abc6",
    likes: 553,
    bookmark: 1054,
    category: "design",
    label: "디자인",
    username: "오지윤",
    title: "등산 앱 램블러 UX UI 개선 및 브랜딩",
    src: "/portfolioPageImg/Image-6.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-5.png",
  },
  {
    id: "abc7",
    likes: 1199,
    bookmark: 1009,
    category: "serviceplan",
    label: "서비스 기획",
    username: "강소정",
    title: "돼지의 피",
    src: "/portfolioPageImg/Image-7.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-6.png",
  },
  {
    id: "abc8",
    likes: 926,
    bookmark: 1193,
    category: "design",
    label: "디자인",
    username: "이서현",
    title: "[UI design] 그룹 스터디 보조 앱 BOATMATE (2023년 하반기 출시예정)",
    src: "/portfolioPageImg/Image-8.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-7.png",
  },
  {
    id: "abc9",
    likes: 435,
    bookmark: 1141,
    category: "serviceplan",
    label: "서비스 기획",
    username: "박은서",
    title: "색각이상자를 위한 지하철 노선도 개선 프로젝트",
    src: "/portfolioPageImg/Image-9.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-8.png",
  },
  {
    id: "abc10",
    likes: 789,
    bookmark: 1186,
    category: "design",
    label: "디자인",
    username: "강소정",
    title: "자기객관화를 통한 감정 관리 서비스",
    src: "/portfolioPageImg/Image-10.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-9.png",
  },
  {
    id: "abc11",
    likes: 1042,
    bookmark: 1236,
    category: "serviceplan",
    label: "서비스 기획",
    username: "삐끼 밍",
    title: "PAYSONA : SNS Finance App",
    src: "/portfolioPageImg/Image-11.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-10.png",
  },
  {
    id: "abc12",
    likes: 1197,
    bookmark: 1364,
    category: "design",
    label: "디자인",
    username: "JU JINHWAN",
    title: "Branding Microsite 'VANS OLDSKOOL CAMPAIGN'",
    src: "/portfolioPageImg/Image-12.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-11.png",
  },
  {
    id: "abc13",
    likes: 826,
    bookmark: 1248,
    category: "serviceplan",
    label: "서비스 기획",
    username: "B",
    title: "Portfolio 2023 - Graphic & Motion design",
    src: "/portfolioPageImg/Image-13.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-12.png",
  },
  {
    id: "abc14",
    likes: 689,
    bookmark: 1289,
    category: "design",
    label: "디자인",
    username: "한유진",
    title: "스튜디오 ENAE - 2023 포트폴리오",
    src: "/portfolioPageImg/Image-14.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-13.png",
  },
  {
    id: "abc15",
    likes: 915,
    bookmark: 1149,
    category: "serviceplan",
    label: "서비스 기획",
    username: "케빈박",
    title: "JUNIVER SCHOOL Character Renewal & UI/UX & Contents Design",
    src: "/portfolioPageImg/Image-15.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-14.png",
  },
  {
    id: "abc16",
    likes: 1076,
    bookmark: 1028,
    category: "design",
    label: "디자인",
    username: "데이빗 정",
    title: "(PROTOTYPE)2023 web design portfolio 전한샘",
    src: "/portfolioPageImg/Image-16.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-15.png",
  },
  {
    id: "abc17",
    likes: 1153,
    bookmark: 1314,
    category: "serviceplan",
    label: "서비스 기획",
    username: "신지윤",
    title: "Welaaa Audiobook APP I UX/UI DESIGN",
    src: "/portfolioPageImg/Image-17.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-16.png",
  },
  {
    id: "abc18",
    likes: 1256,
    bookmark: 1176,
    category: "design",
    label: "디자인",
    username: "김지후",
    title: "TH STUDIO Branding & Website Design",
    src: "/portfolioPageImg/Image-18.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-17.png",
  },
  {
    id: "abc19",
    likes: 589,
    bookmark: 1079,
    category: "serviceplan",
    label: "서비스 기획",
    username: "한지민",
    title: "Graphic Arts with Tripbars",
    src: "/portfolioPageImg/Image-19.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-18.png",
  },
  {
    id: "abc20",
    likes: 998,
    bookmark: 1298,
    category: "design",
    label: "디자인",
    username: "김서윤",
    title: "복잡했던 주문제작 케이크 탐색을 쉽고 즐겁게! 당도 APP 서비스",
    src: "/portfolioPageImg/Image-20.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-19.png",
  },
  {
    id: "abc21",
    likes: 1204,
    bookmark: 1347,
    category: "serviceplan",
    label: "서비스 기획",
    username: "최주원",
    title: "[인천송도] Hellow 페스티벌 2020",
    src: "/portfolioPageImg/Image-21.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-20.png",
  },
  {
    id: "abc22",
    likes: 782,
    bookmark: 1255,
    category: "design",
    label: "디자인",
    username: "Funky Kim",
    title: "[Portfolio] 3D 비주얼 아티스트",
    src: "/portfolioPageImg/Image-22.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-21.png",
  },
  {
    id: "abc23",
    likes: 1123,
    bookmark: 1021,
    category: "serviceplan",
    label: "서비스 기획",
    username: "Neda",
    title: "2023 Neda의 포트폴리오",
    src: "/portfolioPageImg/Image-23.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-0.png",
  },
  {
    id: "abc24",
    likes: 935,
    bookmark: 1233,
    category: "design",
    label: "디자인",
    username: "신지윤",
    title: "UXUI포트폴리오",
    src: "/portfolioPageImg/Image-24.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-1.png",
  },
  {
    id: "abc25",
    likes: 1067,
    bookmark: 1087,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김세호",
    title: "Random Title 1",
    src: "/portfolioPageImg/Image-1.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-2.png",
  },
  {
    id: "abc26",
    likes: 1221,
    bookmark: 1379,
    category: "design",
    label: "디자인",
    username: "김지후",
    title: "Random Title 2",
    src: "/portfolioPageImg/Image-2.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-3.png",
  },
  {
    id: "abc27",
    likes: 1024,
    bookmark: 1202,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김잼",
    title: "Random Title 3",
    src: "/portfolioPageImg/Image-3.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-4.png",
  },
  {
    id: "abc28",
    likes: 887,
    bookmark: 1064,
    category: "design",
    label: "디자인",
    username: "조서아",
    title: "Random Title 4",
    src: "/portfolioPageImg/Image-4.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-5.png",
  },
  {
    id: "abc29",
    likes: 1156,
    bookmark: 1131,
    category: "serviceplan",
    label: "서비스 기획",
    username: "윤수민",
    title: "Random Title 5",
    src: "/portfolioPageImg/Image-5.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-6.png",
  },
  {
    id: "abc30",
    likes: 1423,
    bookmark: 1032,
    category: "design",
    label: "디자인",
    username: "Yumi Bae",
    title: "Random Title 6",
    src: "/portfolioPageImg/Image-6.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-7.png",
  },
  {
    id: "abc31",
    likes: 1190,
    bookmark: 1288,
    category: "serviceplan",
    label: "서비스 기획",
    username: "오지윤",
    title: "Random Title 7",
    src: "/portfolioPageImg/Image-7.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-8.png",
  },
  {
    id: "abc32",
    likes: 1156,
    bookmark: 1232,
    category: "design",
    label: "디자인",
    username: "케빈박",
    title: "Graphic Arts with Tripbars",
    src: "/portfolioPageImg/Image-8.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-15.png",
  },
  {
    id: "abc33",
    likes: 1263,
    bookmark: 1047,
    category: "serviceplan",
    label: "서비스 기획",
    username: "데이빗 정",
    title: "복잡했던 주문제작 케이크 탐색을 쉽고 즐겁게! 당도 APP 서비스",
    src: "/portfolioPageImg/Image-9.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-16.png",
  },
  {
    id: "abc34",
    likes: 1110,
    bookmark: 1325,
    category: "design",
    label: "디자인",
    username: "신지윤",
    title: "Portfolio 2023 - Graphic & Motion design",
    src: "/portfolioPageImg/Image-10.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-17.png",
  },
  {
    id: "abc35",
    likes: 1304,
    bookmark: 1178,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김지후",
    title: "스튜디오 ENAE - 2023 포트폴리오",
    src: "/portfolioPageImg/Image-11.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-18.png",
  },
  {
    id: "abc36",
    likes: 1217,
    bookmark: 1296,
    category: "design",
    label: "디자인",
    username: "한지민",
    title: "JUNIVER SCHOOL Character Renewal & UI/UX & Contents Design",
    src: "/portfolioPageImg/Image-12.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-19.png",
  },
  {
    id: "abc37",
    likes: 1290,
    bookmark: 1116,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김서윤",
    title: "(PROTOTYPE)2023 web design portfolio 전한샘",
    src: "/portfolioPageImg/Image-13.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-20.png",
  },
  {
    id: "abc38",
    likes: 1206,
    bookmark: 1135,
    category: "design",
    label: "디자인",
    username: "최주원",
    title: "Welaaa Audiobook APP I UX/UI DESIGN",
    src: "/portfolioPageImg/Image-14.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-21.png",
  },
  {
    id: "abc39",
    likes: 1292,
    bookmark: 1164,
    category: "serviceplan",
    label: "서비스 기획",
    username: "Funky Kim",
    title: "TH STUDIO Branding & Website Design",
    src: "/portfolioPageImg/Image-15.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-0.png",
  },
  {
    id: "abc40",
    likes: 1176,
    bookmark: 1329,
    category: "design",
    label: "디자인",
    username: "신지윤",
    title: "Graphic Arts with Tripbars",
    src: "/portfolioPageImg/Image-16.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-1.png",
  },
  {
    id: "abc41",
    likes: 1312,
    bookmark: 1255,
    category: "serviceplan",
    label: "서비스 기획",
    username: "Neda",
    title: "복잡했던 주문제작 케이크 탐색을 쉽고 즐겁게! 당도 APP 서비스",
    src: "/portfolioPageImg/Image-17.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-2.png",
  },
  {
    id: "abc42",
    likes: 1135,
    bookmark: 1284,
    category: "design",
    label: "디자인",
    username: "김세호",
    title: "[인천송도] Hellow 페스티벌 2020",
    src: "/portfolioPageImg/Image-18.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-3.png",
  },
  {
    id: "abc43",
    likes: 1234,
    bookmark: 1186,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김세호",
    title: "[Portfolio] 3D 비주얼 아티스트",
    src: "/portfolioPageImg/Image-19.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-4.png",
  },
  {
    id: "abc44",
    likes: 1210,
    bookmark: 1160,
    category: "design",
    label: "디자인",
    username: "김세호",
    title: "2023 Neda의 포트폴리오",
    src: "/portfolioPageImg/Image-20.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-5.png",
  },
  {
    id: "abc45",
    likes: 1245,
    bookmark: 1315,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김세호",
    title: "UXUI포트폴리오",
    src: "/portfolioPageImg/Image-21.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-6.png",
  },
  {
    id: "abc46",
    likes: 1215,
    bookmark: 1347,
    category: "design",
    label: "디자인",
    username: "김세호",
    title: "스튜디오 ENAE - 2023 포트폴리오",
    src: "/portfolioPageImg/Image-22.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-7.png",
  },
  {
    id: "abc47",
    likes: 1283,
    bookmark: 1201,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김세호",
    title: "JUNIVER SCHOOL Character Renewal & UI/UX & Contents Design",
    src: "/portfolioPageImg/Image-23.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-8.png",
  },
  {
    id: "abc48",
    likes: 1205,
    bookmark: 1368,
    category: "serviceplan",
    label: "서비스 기획",
    username: "김세호",
    title: "UXUI포트폴리오",
    src: "/portfolioPageImg/Image-24.png",
    avatarSrc: "/portfolioPageImg/avatarImg/profile-9.png",
  },
];
